version: "3.8"
services:

  # App
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: phalcon-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: phalcon-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: phalcon_app
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: phalcon-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/

  # Redis
  redis:
    container_name: phalcon-redis
    image: redis:6-alpine